
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 23 02:03:14 CST 2012
//----------------------------------------------------

package calclc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LP = 8;
  public static final int res_ = 3;
  public static final int id = 7;
  public static final int mul_ = 4;
  public static final int sum_ = 2;
  public static final int EOF = 0;
  public static final int div_ = 5;
  public static final int numero = 10;
  public static final int error = 1;
  public static final int pos_ = 6;
  public static final int RP = 9;
}

