
package scanner;

/**
 *
 * @author tony
 */
import java.awt.*;
import javax.swing.*;
public class fondo extends javax.swing.JPanel {

    /** Creates new form fondo */
    public fondo() {
        initComponents();
        this.setSize(330,330);
    }

    @Override
public void paintComponent(Graphics g){
    Dimension tam = getSize();
    ImageIcon Ifondo= new ImageIcon(new ImageIcon(getClass().getResource("fondo.jpg")).getImage());
    g.drawImage(Ifondo.getImage(), WIDTH, WIDTH, tam.width,tam.height,null);
    setOpaque(false);
    super.paintComponent(g);
    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
